# Generated by Django 6.0 on 2025-12-26 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shipping', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('confirmed', 'Confirmado'), ('cancelled', 'Cancelado')], default='pending', max_length=20, verbose_name='Estado')),
                ('customer_name', models.CharField(blank=True, max_length=120, verbose_name='Nombre')),
                ('customer_phone', models.CharField(blank=True, max_length=30, verbose_name='Teléfono')),
                ('customer_email', models.EmailField(blank=True, max_length=254, verbose_name='Correo')),
                ('customer_address', models.CharField(blank=True, max_length=220, verbose_name='Dirección')),
                ('notes', models.TextField(blank=True, verbose_name='Notas')),
                ('is_pickup', models.BooleanField(default=False, verbose_name='Retiro en tienda')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Costo de envío')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Subtotal')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Total')),
                ('payment_method', models.CharField(default='Acordar', help_text='Por ahora: Acordar / Contraentrega / Transferencia', max_length=30, verbose_name='Método de pago')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('shipping_zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shipping.shippingzone', verbose_name='Zona de envío')),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=160, verbose_name='Producto')),
                ('variant_description', models.CharField(blank=True, max_length=180, verbose_name='Detalle')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio unitario')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Ítem del pedido',
                'verbose_name_plural': 'Ítems del pedido',
            },
        ),
    ]
