# Generated by Django 6.0 on 2026-01-13 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_user_alter_order_payment_method_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_instructions',
            field=models.TextField(blank=True, help_text='Texto que se mostrará al cliente según el método de pago elegido', verbose_name='Instrucciones de pago'),
        ),
    ]
