# Generated by Django 6.0 on 2026-02-05 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': '📊 Panel de Estadísticas',
                'verbose_name_plural': '📊 Reportes de Ventas',
                'managed': False,
            },
        ),
    ]
