# Generated by Django 6.0 on 2026-01-22 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='variant_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.productimage', verbose_name='Imagen de variante'),
        ),
    ]
