# Generated by Django 6.0 on 2026-02-05 03:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_variant_variant_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True, verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Imagen Categoría')),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Nombre del Color')),
                ('hex_code', models.CharField(help_text='Ej: #0000FF', max_length=7, verbose_name='Código Hex')),
            ],
            options={
                'verbose_name': 'Color',
                'verbose_name_plural': 'Colores',
                'ordering': ['name'],
            },
        ),
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Imagen de Producto', 'verbose_name_plural': 'Imágenes de Producto'},
        ),
        migrations.AlterModelOptions(
            name='variantattribute',
            options={'verbose_name': 'Atributo de Variante', 'verbose_name_plural': 'Atributos de Variante'},
        ),
        migrations.RemoveIndex(
            model_name='variantattribute',
            name='catalog_var_name_078aca_idx',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='sort_order',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(blank=True, max_length=150, verbose_name='Texto Alternativo'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='variant_image',
            field=models.ForeignKey(blank=True, help_text='Si se deja vacío, se usará la imagen principal del producto.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_variants', to='catalog.productimage', verbose_name='Imagen de Variante'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='catalog.category', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='variants', to='catalog.color', verbose_name='Color'),
        ),
    ]
