# Generated by Django 6.0 on 2026-02-06 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_category_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category', '-created_at'], 'verbose_name': 'Producto', 'verbose_name_plural': 'Productos'},
        ),
    ]
